# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dYdT7pJ0Qddu-GF6jL4dmtcb-PZrPrpe

**Task 06: Modifying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

"""Read the RDF file as shown in class"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example5.rdf", format="xml")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

"""

g.add((ns.University, RDF.type, RDFS.Class))
for s, p, o in g:
    print(s, p, o)

"""**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""

g.add((ns.Researcher, RDFS.subClassOf, ns.Person))
for s, p, o in g:
    print(s, p, o)

"""**TASK 6.3: Create a new individual of Researcher named "Jane Smith"**"""

jane_uri = ns.JaneSmith
g.add((jane_uri, RDF.type, ns.Researcher))
for s, p, o in g:
    print(s, p, o)

"""**TASK 6.4: Add to the individual JaneSmith the email address, fullName, given and family names**"""

g.add((jane_uri, ns.email, Literal("jane.smith@university.edu")))
g.add((jane_uri, ns.fullName, Literal("Jane Smith")))
g.add((jane_uri, ns.givenName, Literal("Jane")))
g.add((jane_uri, ns.familyName, Literal("Smith")))
for s, p, o in g:
    print(s, p, o)

"""**TASK 6.5: Add UPM as the university where John Smith works**"""

john_uri = ns.JohnSmith
g.add((john_uri, ns.worksAt, ns.UPM))
for s, p, o in g:
    print(s, p, o)

"""**Task 6.6: Add that Jown knows Jane using the FOAF vocabulary**"""

foaf = Namespace("http://xmlns.com/foaf/0.1/")
g.add((john_uri, foaf.knows, jane_uri))
for s, p, o in g:
    print(s, p, o)